### ISSUE TITLE
Cave Spider is invisible (2.1)

### ISSUE THREAD

**Issue by BlueWither** [Ocelot5836/BetterAnimalsOriginal#1]
<img src="https://i.imgur.com/e91w7KW.png">
Only Optifine. Nomal spiders are visible.

**Comment by cybercat5555** [comment]
To add to this--the cave spider itself is still there, but its model is "sunk" into the ground.

![2018-08-24_15 52 03](https://user-images.githubusercontent.com/17956808/44604986-bc028100-a7b5-11e8-83d9-a0c4d82c09de.png)

**Comment by itsmeow** [comment]
Fixed in my pull request - close upon merge.

**Comment by cybercat5555** [comment]
Fixed as of version 3.0
