### ISSUE TITLE
[Suggestion] - Brown Mooshrooms mod - Compatibility

### ISSUE THREAD

**Issue by DWX12** [Ocelot5836/BetterAnimalsOriginal#19]
Compatibility for the Brown Mooshroom mod, which only adds in a brown mooshroom and nothing else. Figure compatibility for this mod would be fairly straight forward as it would simply be a color variant of the current mooshroom.

https://minecraft.curseforge.com/projects/brown-mooshrooms?gameCategorySlug=mc-mods&projectID=304117

The models look amazing. Great job and thank you so much for all the time and effort put into this mod.

**Comment by itsmeow** [comment]
Oof. This was added like 3 months ago! Forgot to tell you.

**Comment by cybercat5555** [comment]
This has since been added, closing
