### ISSUE TITLE
Suggestion: Animalium and primal core compatibility

### ISSUE THREAD

**Issue by Trinsdar** [Ocelot5836/BetterAnimalsOriginal#24]
Compatibility for animalium and primal core mobs would be nice.
https://minecraft.curseforge.com/projects/animalium
Primal core just adds new kinds of wolves so that would be easy as it would just require retexturing the wolf model. Animalium would probably be harder as it adds new animals which seem to use a little bit different style from vanilla. That's just my opinion on the difficulty of doing them; I'm sure you have a better idea of the difficulty.

**Comment by cybercat5555** [comment]
BA already has Primalcore compat for the steppe wolves, both bears, and even the ovis atre
